### ISSUE TITLE
Dependency on outdated opengl in gemspec

### ISSUE THREAD

**Issue by KoBeWi** [gosu/ashton#44]
If you look at ashton.gemspec, you can see this line:
`s.add_dependency 'opengl', '~> 0.9.0'`

It add dependency on old opengl gem version, which is no longer supported in Ruby 2.0.X (the newest one is 0.10.0). The dependency is artificial, because the new version works just fine. My hacked version of Ashton has this line removed, so I can use it with newest Ruby version.

**Comment by ForeverZer0** [comment]
I really wish this could be fixed, as downgrading Ruby just isn't an option for me.

Is it possible to explain exactly what all needs done to make this work? Simply removing the line doesn't seem to work for me, neither does changing it the version to "0.10" for opengl. I have both versions of opengl installed for Ruby currently, using Ruby 2.4.4 on Windows.

**Comment by ForeverZer0** [comment]
Ah, yeah, that was my problem, my own ignorance not requiring opengl
manually. Thanks for the reply, appreciate it.

**Comment by Spooner** [comment]
Give me a pull request and I'll happily merge it in.

**Comment by jlnr** [comment]
What does everyone think about relaxing the dependency as `'~> 0.9'`? That way existing code doesn't need to be updated (require 'opengl') and it seems to align with the semver philosophy as well. Trying this locally now...

**Comment by jlnr** [comment]
The development dependency on Texplay is also problematic. Stable 0.4.3 does not compile on Windows or macOS, and the precompiled 0.4.3 for 32-bit Windows does not work with my Ruby 2.5 installation either (`irb -rtexplay` fails immediately).

And if I change it to `'texplay', '= 0.4.4.pre'`, I can install Texplay on macOS (and presumably Linux), but that completely locks out Windows.

After updating `rspec`, `rake gem` then works for me. (`rake spec` segfaults :/)

But every Ashton example fails like this:

```
$ ruby -rashton noise_example.rb 
Traceback (most recent call last):
	9: from noise_example.rb:94:in `<main>'
	8: from noise_example.rb:94:in `new'
	7: from noise_example.rb:59:in `initialize'
	6: from noise_example.rb:59:in `new'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/ashton-0.1.5/lib/ashton/shader.rb:68:in `initialize'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/ashton-0.1.5/lib/ashton/shader.rb:105:in `enable'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/ashton-0.1.5/lib/ashton/gosu_ext/window.rb:37:in `gl'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/gosu-0.13.3/lib/gosu/compat.rb:151:in `block (2 levels) in <class:Window>'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/gosu-0.13.3/lib/gosu/swig_patches.rb:65:in `gl'
/usr/local/lib/ruby/gems/2.5.0/gems/gosu-0.13.3/lib/gosu/swig_patches.rb:65:in `unsafe_gl': There is no rendering queue for this operation (RuntimeError)
```

I guess this is something that Ashton users know how to work around? :) @KoBeWi @ForeverZer0 

The good news is that window-to-image rendering has already arrived in Gosu's master branch, and will be released as v0.14. That would be a good time to remove this functionality from Ashton. There's also some stuff in Texplay that uses OpenGL for things that are possible with pure Gosu now. That should make dependency management much easier.

**Comment by KoBeWi** [comment]
That "There is no rendering queue for this operation" thing is usually caused by OpenGL code happening in Window update instead of draw. IIRC, this applies also to drawing on framebuffers and even compiling shaders. Moving everything OpenGL-related to Window.draw should fix it.

**Comment by rubyFeedback** [comment]
The "There is no rendering queue for this operation"  is actually more common than merely OpenGL-related.

I had this problem recently. StackOverflow sort of answered this. (By the way, SO is almost like my number
one resource for learning gosu ... :P )
